//
//  LeetCodeDataSet.swift
//  GetStartedSwift
//
//  Created by Solan Manivannan on 29/05/2018.
//  Copyright © 2018 MyScript. All rights reserved.
//

import Foundation

public let LEETCODE_DATA = [
    ["1", "Two Sum", "/problems/two-sum", "38.3%", "Easy", "Given an array of integers, return  indices  of the two numbers such that they add up to a specific target. \n\n You may assume that each input would have  exactly  one solution, and you may not use the  same  element twice. \n\n Example: \n\n Given nums = [2, 7, 11, 15], target = 9,\n\nBecause nums[ 0 ] + nums[ 1 ] = 2 + 7 = 9,\nreturn [ 0 ,  1 ]."],
    ["2", "Add Two Numbers", "/problems/add-two-numbers", "28.8%", "Medium", "You are given two  non-empty  linked lists representing two non-negative integers. The digits are stored in  reverse order  and each of their nodes contain a single digit. Add the two numbers and return it as a linked list. \n\n You may assume the two numbers do not contain any leading zero, except the number 0 itself. \n\n \n Example \n Input:  (2 -> 4 -> 3) + (5 -> 6 -> 4)\n Output:  7 -> 0 -> 8\n Explanation:  342 + 465 = 807."],
    ["3", "Longest Substring Without Repeating Characters", "/problems/longest-substring-without-repeating-characters", "24.8%", "Medium", "Given a string, find the length of the  longest substring  without repeating characters. \n\n Examples: \n\n Given  \"abcabcbb\" , the answer is  \"abc\" , which the length is 3. \n\n Given  \"bbbbb\" , the answer is  \"b\" , with the length of 1. \n\n Given  \"pwwkew\" , the answer is  \"wke\" , with the length of 3. Note that the answer must be a  substring ,  \"pwke\"  is a  subsequence  and not a substring."],
    ["4", "Median of Two Sorted Arrays", "/problems/median-of-two-sorted-arrays", "23.3%", "Hard", "There are two sorted arrays  nums1  and  nums2  of size m and n respectively. \n\n Find the median of the two sorted arrays. The overall run time complexity should be O(log (m+n)). \n\n Example 1: \n nums1 = [1, 3]\nnums2 = [2]\n\nThe median is 2.0\n \n \n\n Example 2: \n nums1 = [1, 2]\nnums2 = [3, 4]\n\nThe median is (2 + 3)/2 = 2.5\n \n"],
    ["5", "Longest Palindromic Substring", "/problems/longest-palindromic-substring", "25.4%", "Medium", "Given a string  s , find the longest palindromic substring in  s . You may assume that the maximum length of  s  is 1000. \n\n Example 1: \n\n Input:  \"babad\"\n Output:  \"bab\"\n Note:  \"aba\" is also a valid answer.\n \n\n Example 2: \n\n Input:  \"cbbd\"\n Output:  \"bb\"\n \n"],
    ["6", "ZigZag Conversion", "/problems/zigzag-conversion", "27.6%", "Medium", "The string  \"PAYPALISHIRING\"  is written in a zigzag pattern on a given number of rows like this: (you may want to display this pattern in a fixed font for better legibility) \n\n P   A   H   N\nA P L S I I G\nY   I   R\n \n\n And then read line by line:  \"PAHNAPLSIIGYIR\" \n\n Write the code that will take a string and make this conversion given a number of rows: \n\n string convert(string s, int numRows); \n\n Example 1: \n\n Input:  s = \"PAYPALISHIRING\", numRows = 3\n Output:  \"PAHNAPLSIIGYIR\"\n \n\n Example 2: \n\n Input:  s = \"PAYPALISHIRING\", numRows =\u{00a04}\n Output: \u{00a0}\"PINALSIGYAHRPI\"\n Explanation: \n\nP     I    N\nA   L S  I G\nY A   H R\nP     I \n"],
    ["7", "Reverse Integer", "/problems/reverse-integer", "24.4%", "Easy", "Given a 32-bit signed integer, reverse digits of an integer. \n\n Example 1: \n\n Input:  123\n Output:  321\n \n\n Example 2: \n\n Input:  -123\n Output:  -321\n \n\n Example 3: \n\n Input:  120\n Output:  21\n \n\n Note: \nAssume we are dealing with an environment which could only store integers within the 32-bit signed integer range: [\u{22122} 31 ,\u{00a0} 2 31\u{00a0} \u{2212} 1]. For the purpose of this problem, assume that your function returns 0 when the reversed integer overflows. \n"],
    ["8", "String to Integer (atoi)", "/problems/string-to-integer-atoi", "14.1%", "Medium", "Implement  atoi  which\u{00a0}converts a string to an integer. \n\n The function first discards as many whitespace characters as necessary until the first non-whitespace character is found. Then, starting from this character, takes an optional initial plus or minus sign followed by as many numerical digits as possible, and interprets them as a numerical value. \n\n The string can contain additional characters after those that form the integral number, which are ignored and have no effect on the behavior of this function. \n\n If the first sequence of non-whitespace characters in str is not a valid integral number, or if no such sequence exists because either str is empty or it contains only whitespace characters, no conversion is performed. \n\n If no valid conversion could be performed, a zero value is returned. \n\n Note: \n\n \n\t Only the space character  ' '  is considered as whitespace character. \n\t Assume we are dealing with an environment which could only store integers within the 32-bit signed integer range: [\u{22122} 31 ,\u{00a0} 2 31\u{00a0} \u{2212} 1]. If the numerical value is out of the range of representable values, INT_MAX (2 31\u{00a0} \u{2212} 1) or INT_MIN (\u{22122} 31 ) is returned. \n \n\n Example 1: \n\n Input:  \"42\"\n Output:  42\n \n\n Example 2: \n\n Input:  \"   -42\"\n Output:  -42\n Explanation:  The first non-whitespace character is '-', which is the minus sign.\n\u{00a0}            Then take as many numerical digits as possible, which gets 42.\n \n\n Example 3: \n\n Input:  \"4193 with words\"\n Output:  4193\n Explanation:  Conversion stops at digit '3' as the next character is not a numerical digit.\n \n\n Example 4: \n\n Input:  \"words and 987\"\n Output:  0\n Explanation:  The first non-whitespace character is 'w', which is not a numerical \n\u{00a0}            digit or a +/- sign. Therefore no valid conversion could be performed. \n\n Example 5: \n\n Input:  \"-91283472332\"\n Output:  -2147483648\n Explanation:  The number \"-91283472332\" is out of the range of a 32-bit signed integer.\n\u{00a0}            Thefore INT_MIN (\u{22122} 31 ) is returned. \n"],
    ["9", "Palindrome Number", "/problems/palindrome-number", "36.5%", "Easy", "Determine whether an integer is a palindrome. An integer\u{00a0}is\u{00a0a}\u{00a0}palindrome when it\u{00a0}reads the same backward as forward. \n\n Example 1: \n\n Input:  121\n Output:  true\n \n\n Example 2: \n\n Input:  -121\n Output:  false\n Explanation:  From left to right, it reads -121. From right to left, it becomes 121-. Therefore it is not a palindrome.\n \n\n Example 3: \n\n Input:  10\n Output:  false\n Explanation:  Reads 01 from right to left. Therefore it is not a palindrome.\n \n\n Follow up: \n\n Coud you solve\u{00a0}it without converting the integer to a string? \n"]
]
